Задание 1

In [27]:
import numpy as np

arr = np.random.randint(0,100,40)
arre = arr.reshape(5, 8)
arre

array([[28, 39, 90, 55, 56, 36, 63, 22],
       [58, 77, 11, 22, 20, 64, 55, 40],
       [49,  6, 98,  3,  3, 24, 60, 78],
       [60, 15, 60, 37, 84, 32, 50, 98],
       [81, 95, 43, 74, 81, 33, 54, 84]], dtype=int32)

Задание 2

In [35]:
arr=np.zeros(10)
print(arr)
arr= np.arange(10)
arr

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3

In [39]:
arr=np.arange(100,0,-10)
arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

Задание 4

In [47]:
arr=np.random.random(100)
arr

array([0.16819771, 0.26713892, 0.57251993, 0.20314845, 0.25775071,
       0.52611117, 0.16351819, 0.79437932, 0.18904878, 0.60515129,
       0.97066094, 0.25692722, 0.94418234, 0.85039638, 0.91371744,
       0.0457698 , 0.65219167, 0.06403875, 0.46588249, 0.16358319,
       0.75773562, 0.2725601 , 0.75146489, 0.7690186 , 0.3402732 ,
       0.60636896, 0.1907046 , 0.2137801 , 0.57017852, 0.64638934,
       0.57604138, 0.27090023, 0.46206127, 0.00720204, 0.08848881,
       0.92200075, 0.57355839, 0.30611348, 0.90136128, 0.761442  ,
       0.39426644, 0.20288675, 0.23687682, 0.59398219, 0.9918763 ,
       0.57769408, 0.68833408, 0.96600288, 0.08788744, 0.63890097,
       0.71729743, 0.12617351, 0.31426761, 0.63851578, 0.59281947,
       0.04583858, 0.79942581, 0.25500971, 0.30842185, 0.2822786 ,
       0.56283632, 0.35620336, 0.18772481, 0.4087192 , 0.92239462,
       0.71263052, 0.50509818, 0.74999662, 0.78014986, 0.59516497,
       0.1288964 , 0.46989673, 0.04044712, 0.34733056, 0.62822

Задание 5

Задание 6

Задание 7

Задание 8

Задание 9

Задание 10