Задание 1

In [2]:
import numpy as np
from numpy.ma.core import transpose

arr = np.random.randint(0,100,40)
arre = arr.reshape(5, 8)
arre

array([[39, 44, 51, 65, 69, 58,  3, 91],
       [32, 86, 69, 87, 46, 68, 11, 39],
       [22, 80, 10, 65, 81,  8, 56,  2],
       [31, 23, 72, 70, 76, 29, 18, 33],
       [99, 61,  5, 14, 78, 37, 39, 31]], dtype=int32)

Задание 2

In [4]:
arr=np.zeros(10)
print(arr)
arr= np.arange(10)
arr

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3

In [5]:
arr=np.arange(100,0,-10)
arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

Задание 4

In [9]:
a=np.random.rand(100)
p25, p75 = np.percentile(a,[25,75])
print(p25)
print(p75)

0.3191671893669109
0.8173142552471485


Задание 5

In [6]:
A = np.array([
    [2, 1, 1],
    [3, 2, 1],
    [2, 1, 2],
])
transposed = A.T
inverse = np.linalg.inv(A)
print(transposed)
print(inverse)

[[2 3 2]
 [1 2 1]
 [1 1 2]]
[[ 3. -1. -1.]
 [-4.  2.  1.]
 [-1.  0.  1.]]


Задание 6

In [10]:
arr = np.array([1,2,3,4,5,6,7,8])
parts = np.split(arr, 4)
print(parts)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


Задание 7

In [12]:
mat = np.random.randn(4,4)
r = mat[(mat>0.3)&(mat<0.7)]
print(mat)
print(r)

[[ 0.77247049 -0.29393871  0.22236461  0.93547384]
 [-0.20849845  0.83246229  0.0078794   0.05119836]
 [-1.32340521  1.07109436 -1.32542592 -1.02449457]
 [ 0.75780212  0.74806602  1.06868196  0.48542028]]
[0.48542028]


Задание 8

In [15]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
b = np.array([
    [7,8,9],
    [10,11,12]
])

v = np.vstack((a,b))
print(v)
h = np.hstack((a,b))
print(h)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


Задание 9

In [4]:

arr = np.array([1,-2,3,-4,5])
r=np.where(arr< 0, 0, arr)
print(r)

[1 0 3 0 5]


Задание 10

In [5]:
arr = np.array([1,2,3])
parr = np.pad(arr,(0,7),mode='constant', constant_values=0)
print(parr)

[1 2 3 0 0 0 0 0 0 0]
