Задание 1

In [3]:
import numpy as np

arr = np.random.randint(0,100,40)
arre = arr.reshape(5, 8)
arre

array([[95, 17, 43, 63, 42, 62, 43,  7],
       [22, 93, 18, 91, 10, 80, 51, 20],
       [37, 75, 29,  1, 43, 13,  2, 68],
       [82, 28, 14, 59, 59, 14, 50, 29],
       [51, 17, 76, 20, 13, 48, 47,  1]], dtype=int32)

Задание 2

In [4]:
arr=np.zeros(10)
print(arr)
arr= np.arange(10)
arr

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Задание 3

In [5]:
arr=np.arange(100,0,-10)
arr

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

Задание 4

In [6]:
arr=np.random.random(100)
arr

array([1.10837236e-01, 6.44705402e-01, 5.47986003e-02, 1.42453475e-01,
       4.32390958e-02, 4.72470165e-01, 6.67906904e-01, 4.19316956e-01,
       3.02604122e-02, 8.92682786e-01, 2.69765215e-01, 8.54356245e-01,
       1.92486149e-01, 8.65145845e-02, 7.37121574e-01, 5.92697469e-01,
       4.80526284e-01, 2.24069024e-01, 5.75308092e-01, 9.57637076e-01,
       1.78042727e-01, 8.49379725e-01, 1.48858332e-01, 3.85427359e-02,
       5.51175393e-01, 2.89385514e-01, 7.51217024e-01, 8.75766596e-01,
       5.86191160e-02, 4.77877530e-01, 7.37806481e-01, 6.92643705e-01,
       1.46033955e-01, 6.92523236e-02, 4.67425785e-01, 2.02950190e-01,
       9.25120496e-01, 6.87782654e-01, 2.78707087e-01, 9.58389633e-01,
       7.40717822e-01, 8.49630638e-01, 6.51751416e-01, 2.78991549e-01,
       8.04720566e-01, 9.19176021e-01, 5.85836618e-01, 1.06157505e-01,
       7.88880981e-02, 6.08107430e-01, 8.15949378e-02, 8.88644580e-01,
       3.81556221e-01, 4.28405879e-01, 6.47387001e-01, 7.98878077e-01,
      

Задание 5

Задание 6

Задание 7

Задание 8

Задание 9

Задание 10